[package]
name = "gobo-rust"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = "0.8.1"

[[bench]]
name = "lexing"
harness = false

[profile.profiling]
inherits = "release"
debug = true